### ISSUE TITLE
Error when enabling the plug-in with Blender 2.90.1

### ISSUE THREAD

**Issue by alexkaessner** [grantwilk/atomic-data-manager#9]
Hello, I’m not able to activate the plug-in with Blender 2.90.1

I’ve installed the plug-in via the settings install button (and choosing the ZIP file downloaded from the repo). When I try to enable the plug-in in Blender’s settings, the following warning appears:
```
File "/Applications/Blender.app/Contents/Resources/2.90/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
File "/Users/my_username/Library/Application Support/Blender/2.90/scripts/addons/atomic-data-manager/__init__.py", line 30, in <module>
    from atomic_data_manager import ops
ModuleNotFoundError: No module named 'atomic_data_manager'
```

OS: macOS 10.15.7
Blender: Version 2.90.1

**Comment by animate1978** [comment]
This is caused when you download the ZIP from Github, if you download the addon from their website the addon enables correctly

**Comment by alexkaessner** [comment]
@animate1978 Thanks a lot for the hint! That works indeed! 👍
